spring.application.name=movie-review-app
spring.datasource.url=jdbc:postgresql://localhost:5432/movie_review_app
spring.datasource.username=dev_user
spring.datasource.password=dev_password

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
