import type { HomeMovie, Reviewer } from "./homeTypes"

export const topReviewers: Reviewer[] = [
  { id: "r1", name: "Mara Vale", handle: "maravale", avatarColor: "from-amber-400 to-yellow-600", followers: 48200 },
  { id: "r2", name: "Dev Okonkwo", handle: "devwatches", avatarColor: "from-fuchsia-400 to-purple-600", followers: 31900 },
  { id: "r3", name: "Lena Cruz", handle: "lenacinema", avatarColor: "from-cyan-400 to-blue-600", followers: 27400 },
  { id: "r4", name: "Isak Rune", handle: "runeframes", avatarColor: "from-emerald-400 to-teal-600", followers: 19800 },
  { id: "r5", name: "Priya Nair", handle: "priyapix", avatarColor: "from-rose-400 to-red-600", followers: 15300 },
]

export const trendingMovie: HomeMovie = {
  id: "m0",
  title: "Neon Requiem",
  year: 2026,
  genres: ["Sci-Fi", "Thriller", "Noir"],
  runtimeMinutes: 138,
  posterUrl: "/movies/poster-neon-drive.png",
  backdropUrl: "/movies/hero-backdrop.png",
  synopsis:
    "In a rain-drenched megacity that never sleeps, a burnt-out detective chases a ghost through neon-lit alleys — and uncovers a conspiracy humming beneath the city's electric skin.",
  averageRating: 4.7,
  reviewCount: 1284,
  latestReview: {
    id: "rev0",
    author: topReviewers[0],
    rating: 5,
    body: "A hypnotic, gorgeously shot fever dream. Every frame glows.",
    createdAt: "2026-09-18",
  },
}

export const recentlyReviewed: HomeMovie[] = [
  {
    id: "m1",
    title: "Midnight Signal",
    year: 2025,
    genres: ["Drama", "Mystery"],
    runtimeMinutes: 112,
    posterUrl: "/movies/poster-midnight.png",
    synopsis: "A radio host receives calls from a city that no longer exists.",
    averageRating: 4.3,
    reviewCount: 642,
    latestReview: {
      id: "rev1",
      author: topReviewers[2],
      rating: 4.5,
      body: "Slow-burn brilliance with a haunting lead performance. Stayed with me for days.",
      createdAt: "2026-09-16",
    },
  },
  {
    id: "m2",
    title: "Echo Drift",
    year: 2025,
    genres: ["Sci-Fi", "Adventure"],
    runtimeMinutes: 129,
    posterUrl: "/movies/poster-echo.png",
    synopsis: "A lone astronaut drifts toward a signal that sounds like her own voice.",
    averageRating: 4.6,
    reviewCount: 908,
    latestReview: {
      id: "rev2",
      author: topReviewers[1],
      rating: 5,
      body: "The most beautiful sci-fi score of the decade. Genuinely transcendent.",
      createdAt: "2026-09-15",
    },
  },
  {
    id: "m3",
    title: "Crimson Hour",
    year: 2024,
    genres: ["Crime", "Noir"],
    runtimeMinutes: 121,
    posterUrl: "/movies/poster-crimson.png",
    synopsis: "A detective bends every rule to solve the case that broke him.",
    averageRating: 3.9,
    reviewCount: 421,
    latestReview: {
      id: "rev3",
      author: topReviewers[3],
      rating: 4,
      body: "Stylish and mean in all the right ways, even if the third act wobbles.",
      createdAt: "2026-09-14",
    },
  },
  {
    id: "m4",
    title: "Afterglow",
    year: 2025,
    genres: ["Romance", "Drama"],
    runtimeMinutes: 104,
    posterUrl: "/movies/poster-afterglow.png",
    synopsis: "Two strangers share one golden night above a sleepless city.",
    averageRating: 4.1,
    reviewCount: 553,
    latestReview: {
      id: "rev4",
      author: topReviewers[4],
      rating: 4,
      body: "Tender, warm, and quietly devastating. A perfect late-night watch.",
      createdAt: "2026-09-13",
    },
  },
  {
    id: "m5",
    title: "Voltage",
    year: 2026,
    genres: ["Action", "Sci-Fi"],
    runtimeMinutes: 118,
    posterUrl: "/movies/poster-voltage.png",
    synopsis: "A courier wired with stolen energy has 12 hours to stay alive.",
    averageRating: 4.4,
    reviewCount: 776,
    latestReview: {
      id: "rev5",
      author: topReviewers[0],
      rating: 4.5,
      body: "Relentless, kinetic, and dripping with neon. Pure adrenaline cinema.",
      createdAt: "2026-09-12",
    },
  },
]
